server:
  port: 8081
logging:
  level:
    # This silences the Hibernate startup/metadata logs
    org.hibernate: WARN
    # This silences the connection pool logs
    org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl: WARN
spring:
  application:
    name: ems
  datasource:
    url: jdbc:mysql://localhost:3306/ems
    username: root
    password: 2478208
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # Ensure this is set to false if you want to hide SQL queries
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false